export const GET_OR_FETCH_EVENTS = 'GET_OR_FETCH_EVENTS';
export const GET_OR_FETCH_EVENTS_SUCCESS = 'GET_OR_FETCH_EVENTS_SUCCESS';
export const GET_OR_FETCH_EVENTS_ERROR = 'GET_OR_FETCH_EVENTS_ERROR';